// <auto-generated />
namespace SmartHome.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta1-30916")]
    public sealed partial class fixSomeSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixSomeSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201409241146576_fixSomeSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
