//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog : IEntity
    {
        public int ID { get; set; }
        public int ConfigID { get; set; }
        public int ActionID { get; set; }
        public string DeviceState { get; set; }
        public System.DateTime EventDatetime { get; set; }
        public int DeviceTypeID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Device Device { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
