//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Core.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartHomeDBEntities : DbContext
    {
        public SmartHomeDBEntities()
            : base("name=SmartHomeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceType> DeviceTypes { get; set; }
        public DbSet<EventLog> EventLogs { get; set; }
        public DbSet<Sensor> Sensors { get; set; }
        public DbSet<Trigger> Triggers { get; set; }
        public DbSet<SHConfig> SHConfigs { get; set; }
    }
}
