//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trigger : INameEntity
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int DeviceID { get; set; }
        public int SensorID { get; set; }
        public string Condition { get; set; }
        public int DeviceTypeID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
