//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public DeviceType()
        {
            this.Devices = new HashSet<Device>();
            this.DeviceType1 = new HashSet<DeviceType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<DeviceType> DeviceType1 { get; set; }
        public virtual DeviceType DeviceType2 { get; set; }
    }
}
