//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.EventLogs = new HashSet<EventLog>();
        }
    
        public int ID { get; set; }
        public int ConfigTypeID { get; set; }
        public int DeviceTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ConfigType ConfigType { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual ICollection<EventLog> EventLogs { get; set; }
    }
}
