//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int Id { get; set; }
        public int ObjectId { get; set; }
        public string Action { get; set; }
        public string ObjectState { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
